[package]
name = "schema-forge-backend"
version = "0.4.0"
edition = "2021"

[dependencies]
schema-forge-core = { path = "../schema-forge-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
