[package]
name = "schema-forge-core"
version = "0.4.0"
edition = "2021"

[dependencies]
mti = { version = "1.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
proptest = "1"
